
import dc.AsmeniniuFinansuValdymas;
import dc.Islaidos;
import dc.Kategorija;
import dc.Pajamos;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dell
 */
public class view extends javax.swing.JFrame {

    AsmeniniuFinansuValdymas abc = new AsmeniniuFinansuValdymas();
    KategorijuSararasas katsar = new KategorijuSararasas(abc);

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", "", "", null},
                {null, null, "", "", "", null},
                {null, null, "", "", "", null},
                {null, null, "", "", "", null}
            },
            new String [] {
                "Suma", "Data", "Pavadinimas", "Kategorija", "Komentaras", "Cekio numeris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Atnaujinti lenteles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pajamos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", "", ""},
                {null, null, "", "", ""},
                {null, null, "", "", ""},
                {null, null, "", "", ""}
            },
            new String [] {
                "Suma", "Data", "Pavadinimas", "Kategorija", "Komentaras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Islaidos");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Islaidu balansas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Bendras sistemos balansas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Pajamu balansas:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jMenu1.setText("Failas");

        jMenuItem1.setText("Atverti finansu faila");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pradeti nauja finansu valdyma");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Saugoti duomenis faile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Baigti darba");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kategorijos");

        jMenuItem5.setText("Kurti nauja kategorija");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Peržiūrėti kategorijų sąrašą");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem11.setText("Keisti kategorijos pavadinima");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Istrinti kategorija");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Finansai");

        jMenuItem7.setText("Pridėti išlaidas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Pridėti pajamas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem10.setText("Pamatyti norimos kategorijos pajamas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem13.setText("Pamatyti norimos kategorijos islaidas");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Apie");

        jMenuItem9.setText("Apie programą");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFileChooser langas = new JFileChooser();
        langas.setFileFilter(new FileNameExtensionFilter("txt failas", "txt"));
        int rez = langas.showOpenDialog(null);

        if (rez == JFileChooser.APPROVE_OPTION) {
            File failas = langas.getSelectedFile();

            try {
                String pirmaEilute = null;
                BufferedReader in = new BufferedReader(new FileReader(failas));
                String s;

                String temp = null;
                String kt = "Kategorijos:";
                String pj = "Pajamos:";
                String is = "Islaidos:";

                while ((s = in.readLine()) != null) {

                    if (s.trim().endsWith(":")) {
                        temp = s;
                    } else {
                        if (temp.contentEquals(kt)) {
                            String[] duom = s.split(",");
                            String pava = duom[0];
                            String aprasymas = duom[1];
                            abc.pridetiKategorija(pava, aprasymas);
                        } else if (temp.contentEquals(pj)) {
                            String[] duom = s.split(",");
                            Double sum = Double.parseDouble(duom[0]);
                            String pav = duom[1];
                            String is_kategorija = duom[2];
                            String komentaras = duom[3];
                            abc.pridetiPajamas(sum, new Date(), pav, is_kategorija, komentaras);
                        } else {
                            String[] duom = s.split(",");
                            Double sum = Double.parseDouble(duom[0]);
                            String pav = duom[1];
                            String is_kategorija = duom[2];
                            String komentaras = duom[3];
                            String num = duom[4];
                            abc.pridetiIslaida(sum, new Date(), pav, is_kategorija, komentaras, num);
                        }
                    }
                }
            } catch (Exception klaida) {
                System.out.println("Klaida");
                klaida.printStackTrace();
            } finally {
                System.out.println("Duomenys ikelti");
                JOptionPane.showMessageDialog(this, "Duomenys ikelti");
                atnaujintiIslaiduLentele();
                atnaujintiPajamuLentele();
                atnaujintiIslaiduBalansa();
                atnaujintiPajamuBalansa();
                atnaujintiBendraBalansa();
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        abc = new AsmeniniuFinansuValdymas();
        //abc.pridetiKategorija("Kat_pav","Aprasymas" );
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        ArrayList<Kategorija> kat = abc.gautiKategorijuSarasa();
        ArrayList<Islaidos> isl = abc.gautiIslaiduSarasa();
        ArrayList<Pajamos> prp = abc.gautiPajamuSarasa();

        JFileChooser langas = new JFileChooser();
        langas.setFileFilter(new FileNameExtensionFilter("txt failas", "txt"));
        int rez = langas.showSaveDialog(this);
        if (rez == JFileChooser.APPROVE_OPTION) {
            try {
                FileWriter file = new FileWriter(new File(langas.getSelectedFile() + ""));
                for (Pajamos k : prp) {
                    file.write(k.toString());
                    file.write(String.format("%n"));
                }
                for (Islaidos k : isl) {
                    file.write(k.toString());
                    file.write(String.format("%n"));
                }
                for (Kategorija k : kat) {
                    file.write(k.toString());
                    file.write(String.format("%n"));
                }
                JOptionPane.showMessageDialog(this, "Duomenys issaugoti");
                file.close();
            } catch (Exception e) {
                System.out.println("Unable to perform operation");
            }
        }


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Kategorijos kiv = new Kategorijos(this, true, abc);
        kiv.setVisible(true);
        katsar.atnaujintiKategorijuLentele();
        katsar.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         
        katsar.atnaujintiKategorijuLentele();
        katsar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (abc.gautiKategorijuSarasa().size() > 0) {
            IslaiduIvedimas isv = new IslaiduIvedimas(this, true, abc);
            isv.setVisible(true);
            atnaujintiIslaiduLentele();
            atnaujintiIslaiduBalansa();
            atnaujintiBendraBalansa();
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atnaujintiIslaiduLentele();
        atnaujintiPajamuLentele();
        atnaujintiIslaiduBalansa();
        atnaujintiPajamuBalansa();
        atnaujintiBendraBalansa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        if (abc.gautiKategorijuSarasa().size() > 0) {
            PajamuIvedimas pajm = new PajamuIvedimas(this, true, abc);
            pajm.setVisible(true);
            atnaujintiPajamuLentele();
            atnaujintiPajamuBalansa();
            atnaujintiBendraBalansa();
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if (abc.gautiKategorijuSarasa().size() > 0) {
            KeistiKategorijosPavadinima kst = new KeistiKategorijosPavadinima(this, true, abc);
            kst.setVisible(true);
            katsar.atnaujintiKategorijuLentele();
            katsar.repaint();

        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        if (abc.gautiKategorijuSarasa().size() > 0) {
            IstrintiKategorija istr = new IstrintiKategorija(this, true, abc);
            istr.setVisible(true);
            katsar.atnaujintiKategorijuLentele();
            katsar.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if (abc.gautiKategorijuSarasa().size() > 0) {
            KategorijosPajamos kp = new KategorijosPajamos(this, true, abc);
            kp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

        if (abc.gautiKategorijuSarasa().size() > 0) {
            KategorijosIslaidos ki = new KategorijosIslaidos(this, true, abc);
            ki.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite nors viena kategorija");
        }

    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        Apie ap = new Apie();
        ap.setVisible(true);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    public void atnaujintiIslaiduLentele() {
        ArrayList<Islaidos> isl = abc.gautiIslaiduSarasa();
        String[][] mas1 = new String[isl.size()][6];
        int i = 0;
        for (Islaidos s : isl) {
            mas1[i][0] = String.valueOf(s.getsuma());
            mas1[i][1] = String.valueOf(s.getdate());
            mas1[i][2] = s.getpavadinimas();
            mas1[i][3] = s.getkategorija();
            mas1[i][4] = s.getkomentaras();
            mas1[i][5] = s.getnumeris();
            i++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                mas1,
                new String[]{
                    "Suma", "Data", "Pavadinimas", "Kategorija", "Komentaras", "Cekio numeris"
                }
        ));
    }

    public void atnaujintiPajamuLentele() {
        ArrayList<Pajamos> pjm = abc.gautiPajamuSarasa();
        String[][] mas2 = new String[pjm.size()][5];
        int i = 0;
        for (Pajamos p : pjm) {
            mas2[i][0] = String.valueOf(p.getsuma());
            mas2[i][1] = String.valueOf(p.getdate());
            mas2[i][2] = p.getpavadinimas();
            mas2[i][3] = p.getkategorija();
            mas2[i][4] = p.getkomentaras();
            i++;
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                mas2,
                new String[]{
                    "Suma", "Data", "Pavadinimas", "Kategorija", "Komentaras"
                }
        ));
    }

    public void atnaujintiIslaiduBalansa() {
        String[][] mas3 = new String[1][1];
        int i = 0;
        mas3[0][0] = String.valueOf(abc.gautiIslaiduBalansa());
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                mas3,
                new String[]{
                    "Islaidu balansas:"
                }
        ));
    }

    public void atnaujintiPajamuBalansa() {
        String[][] mas4 = new String[1][1];
        int i = 0;
        mas4[0][0] = String.valueOf(abc.gautiPajamuBalansa());
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
                mas4,
                new String[]{
                    "Pajamu balansas:"
                }
        ));
    }

    public void atnaujintiBendraBalansa() {
        String[][] mas5 = new String[1][1];
        int i = 0;
        mas5[0][0] = String.valueOf(abc.gautiPajamuBalansa() + abc.gautiIslaiduBalansa());
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                mas5,
                new String[]{
                    "Bendras sistemos balansas:"
                }
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
